M48
; DRILL file KiCad 10.0.1 date 2026-06-20T14:21:54
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-20T14:21:54-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.250
%
G90
G05
T1
X115.68Y-134.8
X188.28Y-134.8
T2
X146.11Y-66.075
X157.54Y-66.075
M30
